site_name: Email Client with Dependency Injection
site_description: Professional email client using component-based architecture with monkey-patching dependency injection
site_url: https://github.com/adithyab-20/ospsd-ta-task

repo_name: ospsd-ta-task
repo_url: https://github.com/adithyab-20/ospsd-ta-task
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_signature_annotations: true
            merge_init_into_class: true
            separate_signature: true
          paths: [src/email_api/src, src/gmail_impl/src]

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/index.md
  - Architecture:
      - Design Philosophy: architecture/design-philosophy.md
      - Dependency Injection: architecture/dependency-injection.md
      - Testing Strategy: architecture/testing.md
  - API Reference:
    - Email API: reference/email-api.md
    - Gmail Implementation: reference/gmail-impl.md

# Copyright
copyright: "&copy; 2024-2025 Email Client. Licensed under MIT License."
