[project]
name = "mail_client_service"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["fastapi", "uvicorn"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"